### PR TITLE
aks updated - Andrei

### PR DESCRIPTION
**Pull request by Soprano37**
Updated - cluster working OK

### CODE REVIEW

**Comment by piyushsachdeva** [comment]
This repo is part of a video tutorial hence, I cannot approve the PR.

**Comment by Soprano37** [comment]
Yes, sorry, It was by mistake. I was going to merge the PR into my repo. I
did not notice it was going to yours. Please reject if it happens again.

Regards,
Andrei.

**Comment by Soprano37** [comment]
Piyush,

Great video tutorial btw! It's helping me with job interview and at work to
ensure any secrets are not exposed.
Just ignore my PR

Regards,
Andrei.
Sydney, Australia.

**Comment by piyushsachdeva** [comment]
Thank you so much, Andrei, for the fantastic feedback. I am glad it was helpful :)
Have a great day!

**Pull request closed without merging**
